# .streamlit/config.toml

[theme]
base="dark"
primaryColor="#90CAF9"  # Light Blue - For interactive elements like sliders, buttons
backgroundColor="#1E1E1E" # Dark Gray - Main background
secondaryBackgroundColor="#2D2D2D" # Slightly lighter Dark Gray - For containers, sidebars
textColor="#E0E0E0" # Light Gray - Primary text color
font="sans serif"
